# Generated by Django 4.2 on 2023-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('private_key', models.CharField(max_length=64, verbose_name='Приватный ключ')),
                ('public_key', models.CharField(max_length=42, verbose_name='Публичный ключ')),
            ],
        ),
    ]
