# Generated by Django 4.2 on 2023-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_manager', '0002_alter_wallet_private_key_alter_wallet_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=66, unique=True, verbose_name='Приватный ключ'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(max_length=44, unique=True, verbose_name='Публичный ключ'),
        ),
    ]
