version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5456:5432"
    env_file:
        - ./.env.dev
#  redis:
#    image: redis:6.2.5-alpine3.14
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --appendonly yes
#    depends_on:
#      - web
#  celery:
#    build: ./backend
#    command: celery -A crm worker -l info
#    volumes:
#      - ./backend/:/usr/src/backend/
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db
#      - redis

volumes:
  postgres_data:
#  redis_data:
  backend: